[package]
name = "balthazar"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive", "env"] }
eyre = "0.6.7"
thiserror = { version = "1.0.30" }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "tracing"] }

opentelemetry = { optional = true, version = "0.17.0" }
opentelemetry-jaeger = { optional = true, version = "0.16.0" }
tracing = { optional = true, version = "0.1.31" }
tracing-opentelemetry = { optional = true, version = "0.17.2" }
tracing-subscriber = { optional = true, version = "0.3.9" }
tracing-tree = { optional = true, version = "0.2.0" }
postgres = { optional = true, version = "0.19.2" }
sqlx = { optional = true, version = "0.5.11" }

[features]
default = ["logging"]
logging = [
    "opentelemetry",
    "opentelemetry/rt-tokio",
    "opentelemetry-jaeger",
    "opentelemetry-jaeger/rt-tokio",
    "opentelemetry-jaeger/collector_client",
    "opentelemetry-jaeger/reqwest_collector_client",
    "tracing",
    "tracing-opentelemetry",
    "tracing-subscriber",
    "tracing-subscriber/env-filter",
    "tracing-tree"
]
database = [
    "postgres",
    "sqlx",
    "sqlx/postgres",
    "sqlx/runtime-tokio-rustls",
]
