[package]
name = "balthazar"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["derive", "env"] }
color-eyre = "0.6"
eyre = "0.6"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "tracing", "signal"] }
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio", "collector_client", "reqwest_collector_client"] }
serde = { version = "1.0.136", features = ["derive"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tree = "0.2"

postgres = { optional = true, version = "0.19" }
sqlx = { optional = true, version = "0.5" }
async-trait = "0.1.52"
futures-util = "0.3.21"
ethereum-types = "0.13.1"

[features]
database = [
    "postgres",
    "sqlx",
    "sqlx/postgres",
    "sqlx/runtime-tokio-rustls",
]
