[package]
name = "balthazar"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive", "env"] }
color-eyre = "0.6.1"
eyre = "0.6.7"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "tracing"] }
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio", "collector_client", "reqwest_collector_client"] }
tracing = "0.1.31"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
tracing-tree = "0.2.0"

postgres = { optional = true, version = "0.19.2" }
sqlx = { optional = true, version = "0.5.11" }

[features]
database = [
    "postgres",
    "sqlx",
    "sqlx/postgres",
    "sqlx/runtime-tokio-rustls",
]
