[package]
name = "balthazar"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1"
clap = { version = "3.1", features = ["derive", "env"] }
color-eyre = "0.6"
chrono = "0.4"
ethereum-types = "0.13"
eyre = "0.6"
futures-util = "0.3"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio", "collector_client", "reqwest_collector_client"] }
quickcheck = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-serde = "0.1"
http = "0.2"
reqwest = "0.11"
tower-http = { version = "0.3", features = ["trace"] }
axum = { version = "0.5", features = ["headers"] }
strum = { version = "0.24", features = ["derive"] }
time = { version = "0.3", features = ["quickcheck", "serde", "serde-well-known"] }
tokio = { version = "1.17", features = ["rt-multi-thread", "macros", "tracing", "signal"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tree = "0.2"
uuid = { version = "1.0", features = ["serde", "v4"] }
vergen = { version = "7.2.1" }

# database
sqlx = { optional = true, version = "0.5" }
postgres = { optional = true, version = "0.19" }

# redis
bb8-redis = { optional = true, version = "0.11" }

[features]
postgres = [
    "dep:postgres",
    "sqlx",
    "sqlx/postgres",
    "sqlx/runtime-tokio-rustls",
    "sqlx/uuid",
    "sqlx/time"
]
redis = [
    "bb8-redis"
]
